@startuml "Diagrama de Despliegue - Yupay Finance"
skinparam linetype ortho

node "Navegador del Usuario / Cliente" as Browser

cloud "Vercel (Frontend Hosting)" as VercelNode {
  artifact "yupay-frontend" {
    component "React SPA (Single Page Application)" as ReactApp
  }
}

cloud "Render (Web Service)" as RenderNode {
  artifact "yupay-backend (Node.js)" {
    package "Monolito Modular (API RESTful)" {
      component "Identity & Access Module" as IAM
      component "Simulation Module" as Sim
      component "Catalog & Risk Module" as Cat
      component "Billing & Subscriptions Module" as Bill
      component "Monitoring & Alerts Module" as Notif
    }
    component "Prisma ORM" as Prisma
  }
}

cloud "Supabase (DBaaS)" as SupabaseNode {
  database "PostgreSQL Database" as PostgresDB
}

cloud "Payment Gateway\n(Stripe / Niubiz)" as PaymentProvider
cloud "SendGrid / Email Service" as SendGrid

' Interacciones del Usuario
Browser --> VercelNode : 1. Solicita la web (HTTPS)
VercelNode ..> Browser : 2. Descarga SPA al navegador
Browser --> RenderNode : 3. Peticiones API (HTTPS / REST)

' Conexión Interna a Base de Datos
RenderNode --> SupabaseNode : 4. Consultas a BD (TCP/IP)
Prisma ..> PostgresDB : Gestiona esquemas y queries

' Conexiones a Servicios Externos (Release 02)
Bill --> PaymentProvider : HTTPS (Procesa pagos de suscripción Pro)
Notif --> SendGrid : HTTPS (Envía correos de alerta crítica)

@enduml