@startuml
left to right direction
actor "Usuario" as user
actor "BD Financiera" as bd

rectangle "Yupay Finance" {
    usecase "Consultar entidades financieras" as UC_consultar
    usecase "Ver listado ordenado por tasa" as UC_listar
    usecase "Filtrar resultados por criterios" as UC_filtrar
}

user --> UC_consultar
user --> UC_filtrar

UC_consultar ..> UC_listar : <<include>>
UC_filtrar ..> UC_listar : <<extend>>
bd --> UC_consultar
@endum