@startuml
left to right direction
actor "User" as user
actor "Financial Database" as bd

rectangle "Yupay Finance" {
    usecase "Query financial institutions" as UC_consultar
    usecase "View list sorted by rate" as UC_listar
    usecase "Filter results by criteria" as UC_filtrar
}

user --> UC_consultar
user --> UC_filtrar

UC_consultar ..> UC_listar : <<include>>
UC_filtrar ..> UC_listar : <<extend>>
bd --> UC_consultar
@enduml