@startuml
autonumber

actor User as usr
boundary YupayFinanceApp as app
control SimulatorController as ctrl
entity "newSimulation:Simulation" as SimulationObj
database Database as db

usr -> app: inputData(amount, currency, term)
activate app
app -> ctrl: calculateYield(amount, currency, term)
activate ctrl

create SimulationObj
ctrl -> SimulationObj: new(amount, currency, term)
ctrl -> SimulationObj: calculateInterest()
activate SimulationObj
SimulationObj --> ctrl: calculatedYield
deactivate SimulationObj

ctrl --> app: returnResults
deactivate ctrl
app --> usr: displayYieldAndRisk

== Save to Profile Action ==
usr -> app: click "Save Simulation"
app -> ctrl: saveToUserHistory(userId, newSimulation)
activate ctrl
ctrl -> db: INSERT INTO saved_simulations(...)
activate db
db --> ctrl: successConfirmation
deactivate db
ctrl --> app: saveSuccess
deactivate ctrl
app --> usr: show message "Simulation saved to your profile"
deactivate app

@enduml