@startuml "Casos de Uso - Generar Reporte de Solvencia"

' Estilo profesional y limpio
skinparam actorStyle awesome
skinparam packageStyle rectangle
skinparam usecase {
    BackgroundColor #F3F9FF
    BorderColor #2B88D9
    ArrowColor #2B88D9
    ActorBorderColor #2B88D9
    ActorBackgroundColor #F3F9FF
}

actor "User" as user

package "Yupay Finance" {
    usecase "Generate solvency report" as UC_reporte
    usecase "Query financial history in Database" as UC_historial
    usecase "Download report as PDF" as UC_pdf
}

user --> UC_reporte

UC_reporte ..> UC_historial : <<include>>
UC_pdf ..> UC_reporte : <<extend>>

@enduml
