@startuml "Casos de Uso - Visualizar Semáforo de Riesgo"

' Estilo profesional y limpio
skinparam actorStyle awesome
skinparam packageStyle rectangle
skinparam usecase {
    BackgroundColor #F3F9FF
    BorderColor #2B88D9
    ArrowColor #2B88D9
    ActorBorderColor #2B88D9
    ActorBackgroundColor #F3F9FF
}

actor "User" as user

package "Yupay Finance - US04" {
    usecase "Search investment alternatives" as UC_buscar
    usecase "Visualize risk traffic light" as UC_semaforo
    usecase "Query SBS rating in Database" as UC_bd
}

user --> UC_buscar

UC_buscar ..> UC_semaforo : <<include>>
UC_semaforo ..> UC_bd : <<include>>

@enduml
