@startuml "Casos de Uso - Visualizar Semáforo de Riesgo"

' Estilo profesional y limpio
skinparam actorStyle awesome
skinparam packageStyle rectangle
skinparam usecase {
    BackgroundColor #F3F9FF
    BorderColor #2B88D9
    ArrowColor #2B88D9
    ActorBorderColor #2B88D9
    ActorBackgroundColor #F3F9FF
}

actor "Usuario" as user

package "Yupay Finance - US04" {
    usecase "Buscar alternativas de inversión" as UC_buscar
    usecase "Visualizar semáforo de riesgo" as UC_semaforo
    usecase "Consultar calificación SBS en BD" as UC_bd
}

user --> UC_buscar

UC_buscar ..> UC_semaforo : <<include>>
UC_semaforo ..> UC_bd : <<include>>

@enduml
