@startuml "Class Diagram - Catálogo y Riesgo Financiero"

package CatalogRiskBC {
    
    package FinancialEntityAggregate {
        class FinancialEntity <<AggregateRoot>> {
            - EntityId id
            - String commercialName
            - EntityType type
            - FSDCoverage fsdCoverage
            ' Métodos de comportamiento (El AR orquesta todo)
            + evaluateRisk(color: TrafficLightColor, evaluationDate: DateTime, pdfUrl: String)
            + registerNewProduct(productName: String, type: InstrumentType, rate: InterestRate)
            + updateProductRate(productId: ProductId, newRate: InterestRate)
            + getAvailableProducts(): List<FinancialProduct>
        }
        
        class EntityId <<ValueObject>> {
            - Long value
        }
        
        enum EntityType <<ValueObject>> {
            BANK
            MUNICIPAL_CAJA
            RURAL_CAJA
        }
        
        class FSDCoverage <<ValueObject>> {
            - boolean isActive
            - Money maxCoverageAmount
            + validateCoverage(amount: Money): boolean
        }
        
        class FinancialProduct <<Entity>> {
            - ProductId id
            - String productName
            - InstrumentType instrumentType
            ' Solo accesible a través del AR
            ~ updateRates(newRate: InterestRate)
        }
        
        class ProductId <<ValueObject>> {
            - Long value
        }
        
        class InterestRate <<ValueObject>> {
            - BigDecimal tea
            - BigDecimal trea
            + isGreaterThan(other: InterestRate): boolean
        }
        
        class RiskReport <<Entity>> {
            - ReportId id
            - DateTime evaluationDate
            - String economistPdfUrl
            ' Solo accesible a través del AR
            ~ updateTrafficLight(color: TrafficLightColor)
        }
        
        class ReportId <<ValueObject>> {
            - Long value
        }
        
        enum TrafficLightColor <<ValueObject>> {
            GREEN
            YELLOW
            RED
        }
    }
}

package SharedBC {
    class Money <<ValueObject>> {
        - BigDecimal amount
        - String currency
    }
    enum InstrumentType <<ValueObject>> {
        SAVINGS
        FIXED_TERM
    }
}

' Relaciones estructurales del Agregado FinancialEntity
FinancialEntity "1" *--> "1" EntityId
FinancialEntity "1" *--> "1" EntityType
FinancialEntity "1" *--> "1" FSDCoverage

' Relaciones de contención hacia otras entidades internas
FinancialEntity "1" *--> "0..1" RiskReport
FinancialEntity "1" *--> "0..*" FinancialProduct

' Composición del FinancialProduct
FinancialProduct "1" *--> "1" ProductId
FinancialProduct "1" *--> "1" InterestRate
FinancialProduct "1" *--> "1" InstrumentType

' Composición del RiskReport
RiskReport "1" *--> "1" ReportId
RiskReport "1" *--> "1" TrafficLightColor

' Relación con el Shared Kernel
FSDCoverage "1" *--> "1" Money

@enduml